<li class=""><a href="{dede:field name='typeurl'/}" target="_self">{dede:field name='typename'/}</a>
              <div class="Y center" style="top: 71px; padding-bottom: 0px; width: 128px; left: -2000px; display: none; overflow: hidden; height: 174px; padding-top: 0px; margin-top: 0px; margin-bottom: 0px;">
                <ul>
                {dede:channel type='son' noself='yes'}
                  <li class="first"><a href="[field:typelink/]" target="_self" style="float: none; display: block;">[field:typename/]</a></li>
                   {/dede:channel}
                </ul>
              </div>
            </li>