<li>
              <div class="img"><img src="[field:picname/]" onload="loadImage(this,165,123)" alt="[field:title/]" onerror="loadImageError(this,&#39;.img&#39;)" style="width: 165px; height: 109.725px; padding: 6px 0px;"></div>
              <div class="t-content">
                <div class="name"><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></div>
                <p class="txt">[field:description function='cn_substr(@me,180)'/]...</p>
                <div class="time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
              </div>
            </li>