<?php
$z[0]=Array("flink","  [field:link /]  ",240,318);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="10";
$z[0][4]['type']="text";
$z[1]=Array("channelartlist","\r\n        <a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\r\n       ",458,616);
$z[1][4]['typeid']="1";
$z[2]=Array("global","",766,787);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",856,882);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",921,945);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",1073,1095);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",1167,1184);
$z[6][4]['name']="em";
$z[7]=Array("global","",1274,1306);
$z[7][4]['name']="cfg_templets_skin";

?>