<?php
$z[0]=Array("global","",132,164);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n          <li class=\"\"><a href=\"{dede:field name='typeurl'/}\" target=\"_self\">{dede:field name='typename'/}</a>\r\n            <div class=\"Y center\" style=\"top: 71px; padding-bottom: 0px; width: 128px; left: -2000px; display: none; overflow: hidden; height: 174px; padding-top: 0px; margin-top: 0px; margin-bottom: 0px;\">\r\n              <ul>\r\n                {dede:channel type='son' noself='yes'}\r\n                <li class=\"first\"><a href=\"[field:typelink/]\" target=\"_self\" style=\"float: none; display: block;\">[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </div>\r\n          </li>\r\n          ",553,1250);
$z[1][4]['typeid']="top";

?>